# Generated by Django 5.2.6 on 2025-09-10 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_devices_disk_internal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='location_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.locationzones'),
        ),
    ]
