# Generated by Django 5.2.6 on 2025-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_locations_location_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebuilds',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicedisks',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicemarks',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicemodels',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceprocessors',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicerams',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicesystems',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicetypes',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
