# Generated by Django 5.2.6 on 2025-09-22 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_devicebuilds_is_deprecated_devicedisks_is_deprecated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('code_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.PositiveIntegerField(default=1)),
                ('is_core', models.BooleanField(default=False)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares_by_creator', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares_by_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_softwares',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeviceSoftwares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_softwares', to='api.devices')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_devices', to='api.softwares')),
            ],
            options={
                'db_table': 'api_device_softwares',
                'managed': True,
                'unique_together': {('device', 'software')},
            },
        ),
    ]
