# Generated by Django 5.2.6 on 2025-09-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_softwares_devicesoftwares'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_alerts', models.PositiveIntegerField(default=5)),
                ('items_title_min_length', models.PositiveIntegerField(default=3)),
                ('items_title_max_length', models.PositiveIntegerField(default=100)),
                ('items_title_code_name_length', models.PositiveIntegerField(default=50)),
                ('items_code_name_max_length', models.PositiveIntegerField(default=50)),
                ('username_min_length', models.PositiveIntegerField(default=3)),
                ('username_max_length', models.PositiveIntegerField(default=50)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('password_max_length', models.PositiveIntegerField(default=128)),
                ('email_min_length', models.PositiveIntegerField(default=5)),
                ('email_max_length', models.PositiveIntegerField(default=254)),
                ('name_min_length', models.PositiveIntegerField(default=2)),
                ('name_max_length', models.PositiveIntegerField(default=100)),
                ('default_page_size', models.PositiveIntegerField(default=20)),
                ('default_page_size_options', models.CharField(default='10,20,50,100', max_length=100)),
                ('search_min_input_length', models.PositiveIntegerField(default=2)),
                ('search_max_input_length', models.PositiveIntegerField(default=100)),
                ('default_ordering_column', models.CharField(default='id', max_length=100)),
                ('show_deprecated_only_in', models.CharField(default='admin', max_length=100)),
            ],
            options={
                'db_table': 'api_app_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('default_language', models.CharField(default='en', max_length=20)),
                ('default_theme', models.CharField(default='light', max_length=20)),
                ('date_format_day', models.CharField(choices=[('numeric', 'numeric'), ('2-digit', '2-digit')], default='numeric', max_length=10)),
                ('date_format_month', models.CharField(choices=[('numeric', 'numeric'), ('2-digit', '2-digit')], default='numeric', max_length=10)),
                ('date_format_year', models.CharField(choices=[('numeric', 'numeric'), ('2-digit', '2-digit')], default='numeric', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('time_24h', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_user_settings',
                'managed': True,
            },
        ),
    ]
