# Generated by Django 5.2.6 on 2025-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appsettings_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='default_ordering_column',
            field=models.CharField(default='created_at', max_length=100),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_page_size_options',
            field=models.CharField(default='10,20,30,40,50,100', max_length=100),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='show_deprecated_only_in',
            field=models.CharField(default='models,systems,builds,processors,rams,disks,softwares', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='date_format_day',
            field=models.CharField(choices=[('numeric', 'numeric'), ('2-digit', '2-digit')], default='2-digit', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='date_format_month',
            field=models.CharField(choices=[('numeric', 'numeric'), ('2-digit', '2-digit')], default='2-digit', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
