# Generated by Django 5.2.6 on 2025-09-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appsettings_default_ordering_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicebuilds',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicedisks',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicemarks',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicemodels',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deviceprocessors',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicerams',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicesystems',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicetypes',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locations',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locationzones',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
    ]
