# Generated by Django 5.2.6 on 2025-09-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_devicebuilds_is_core_alter_devicedisks_is_core_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesoftwares',
            name='installed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
