# Generated by Django 5.2.6 on 2025-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_devicesoftwares_installed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='softwares',
            field=models.ManyToManyField(related_name='devices_softwares', through='api.DeviceSoftwares', to='api.softwares'),
        ),
    ]
